application: kurtduranyalcin
version: 1
runtime: python27
api_version: 1
threadsafe: yes

libraries:
- name: jinja2
  version: latest

- name: webapp2
  version: "2.5.2"

handlers:
- url: /static
  static_dir: static

- url: /favicon.ico
  static_files: static/favicon.ico
  upload: static/favicon.ico

- url: .*
  script: main.app
